 - hosts: vagrant
   become: yes
   vars_files:
     - vars/main.yml
       
   tasks:
      - name: Checking if public keys directory exists..
        file: dest=public_keys state=directory
      - name: Set up public keys
        authorized_key: user=vagrant key="{{ lookup('file', item) }}"
        with_fileglob:
            - public_keys/*

      - name: sshd configuration file update
        template: src=templates/sshd_config.j2
            dest=/etc/ssh/sshd_config
            backup=yes
            owner=0 group=0 mode=0644
            validate='/usr/sbin/sshd -T -f %s'
        notify:
          - restart ssh
   handlers:
       - name: restart ssh
         service: name=ssh state=restarted

        
