 - hosts: vagrant
   become: yes
   vars:
       - vhosts: "{{ hostvars[inventory_hostname].enabled_vhosts }}"
   vars_files:
       - vars/mysql.yml
       - vars/apache.yml
   pre_tasks: 
       - set_fact: 
            apache_vhosts: "{{ lookup('template', 'templates/apache_vhosts.j2')|from_yaml }}"
   roles: 
       - { role: geerlingguy.mysql }
       - { role: geerlingguy.apache }
       - role: ansible-letsencrypt
         letsencrypt_webroot_path: /var/www/lte.didgt.info/public
         letsencrypt_email: gc@didgt.info
         letsencrypt_server: https://acme-staging.api.letsencrypt.org/directory
         letsencrypt_cert_domains: 
          - lte.didgt.info
         letsencrypt_renewal_command_args: '--renew-hook "service apache2 reload"'
   tasks:
      - name: Checking if public keys directory exists..
        file: dest=public_keys state=directory
      - name: Set up public keys
        authorized_key: user=vagrant key="{{ lookup('file', item) }}"
        with_fileglob:
            - public_keys/*
      - name: Create Document Roots
        file: path={{ item.documentroot }} state=directory owner=www-data group=www-data mode=0775 recurse=yes
        with_items: "{{ apache_vhosts }}"

        
