- hosts: vagrant
  tasks:
      - name: Checking if public keys directory exists..
        file: dest=public_keys state=directory
      - name: Set up public keys
        authorized_key: user=vagrant key="{{ lookup('file', item) }}"
        with_fileglob:
            - public_keys/*
